ROOTDIR ?= ../..

include $(ROOTDIR)/Makefile.defaults

awa_easymde_dir=$(ROOTDIR)/plugins/awa-easymde
awa_easymde_install_dirs=web
awa_easymde_install_files=MIT-LICENSE.txt

$(eval $(call awa_install_plugin,awa_easymde))

