ROOTDIR ?= ../..

include $(ROOTDIR)/Makefile.defaults

awa_markedit_dir=$(ROOTDIR)/plugins/awa-markedit
awa_markedit_install_dirs=bundles web
awa_markedit_install_files=MIT-LICENSE.txt

$(eval $(call awa_install_plugin,awa_markedit))

