ROOTDIR ?= ../..

include $(ROOTDIR)/Makefile.defaults

awa_trumbowyg_dir=$(ROOTDIR)/plugins/awa-trumbowyg
awa_trumbowyg_install_dirs=web
awa_trumbowyg_install_files=MIT-LICENSE.txt

$(eval $(call awa_install_plugin,awa_trumbowyg))

